CREATE SEQUENCE IF NOT EXISTS api_keys_id_seq START 1;

CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT DEFAULT NEXTVAL('api_keys_id_seq') PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,  -- Store key name
    key TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '90 days'),
    is_revoked BOOLEAN DEFAULT FALSE
);
