services:
  client:
    build: ./client
    ports:
      - "8080:80"
    restart: unless-stopped

  controller:
    build: ./controller
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/spidev0.0:/dev/spidev0.0"
    environment:
      - BLINKA_FORCEBOARD=RaspberryPi4
      - BLINKA_FORCECHIP=BCM2XXX
    volumes:
      - "/sys:/sys:ro"
      - "/proc/device-tree:/proc/device-tree:ro"
      - "/dev:/dev"

  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
