services:
  client:
    build: ./client
    ports:
      - "8080:80"
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - REGION=${REGION}
      - BUCKET_NAME=${BUCKET_NAME}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET=${SECRET}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
