name: Build and Test on PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize  # Ensure CI runs when new commits are pushed to the PR

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      controller: ${{ steps.filter.outputs.controller }}
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Modified Files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            controller:
              - 'controller/**'
            client:
              - 'client/**'
            server:
              - 'server/**'

  build-controller:
    needs: filter
    if: needs.filter.outputs.controller == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Test Controller
        run: |
          cd controller
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest

  build-client:
    needs: filter
    if: needs.filter.outputs.client == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Run Format Check
        run: |
          cd client
          npm run check-format

  build-server:
    needs: filter
    if: needs.filter.outputs.server == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd server
          npm install

      - name: Run Format Check
        run: |
          cd server
          npm run check-format
