name: Client Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'client/**'

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd client
          npm ci

      - name: Run Tests in Headless Chrome
        run: |
          cd client
          npm run test -- --browsers=ChromeHeadless --watch=false
        env:
          CHROME_BIN: /usr/bin/google-chrome
