name: Client Build & Format Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js with Caching
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install Dependencies
        run: |
          cd client
          npm ci

      - name: Check format
        run: |
          cd client
          npm run check-format
