name: Controller Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "controller/**"

jobs:
  build-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python with Caching
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "controller/requirements.txt"

      - name: Install Dependencies
        run: |
          cd controller
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build & Test Controller
        run: |
          cd controller
          source venv/bin/activate
          pytest
          black --check .
