name: Server Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'server/**'

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Test Server
        run: |
          cd server
          npm ci
          npm run check-format
          npm test
