name: Server Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "server/**"

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js with Caching
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: Install Dependencies
        run: |
          cd server
          npm ci

      - name: Build & Test Server
        run: |
          cd server
          npm test
          npm run check-format
